version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  build:
    desc: Build
    cmds:
      - goreleaser --snapshot --rm-dist

  dependencyUpdates:
    desc: Show dependency updates
    deps: [ install-go-mod-outdated ]
    cmds:
      - go mod download
      - go mod tidy
      - go list -u -m -json all | go-mod-outdated -update -direct

  install-go-mod-outdated:
    cmds:
      - go install github.com/psampaz/go-mod-outdated@v0.9.0
      - asdf reshim golang
    status:
      - asdf which go-mod-outdated
